### ISSUE TITLE
No pipeline

### ISSUE THREAD

**Issue by bsul24** [irenebuck/Geocoding-Microservice#4]
As of right now, I don't see a way to actually connect this microservice to my main program. It is very self-contained in that the program is run on its own, and it requests, receives, and displays all the data just to itself. However, there should be a way for another program to make calls to this microservice and actually receive data that it can then use. This could be done by providing a REST API, for example.

**Comment by irenebuck** [comment]
Import zmq to your app.py equivalent of your application and use the equivalent of the get_coordinates() function to access the microservice.
